"""
pdf_generator.py
~~~~~~~~~~~~~~~~
Publication-grade PDF dossier generator for IBM Bob 2.0 - Polyglot Navigator
& Safe Refactor Engine.

Requires:
    reportlab >= 4.0.0
    pillow    >= 10.0.0
    matplotlib>= 3.8.0   (for topology diagram)

Public API
----------
    build_pdf(ast_result: dict, project_name: str, output_path: str) -> str
        Writes the dossier PDF to *output_path* and returns the path.
"""

from __future__ import annotations

import io
import math
import os
from collections import defaultdict
from datetime import datetime, timezone
from typing import Any

# ---------------------------------------------------------------------------
# ReportLab imports - all guarded so linters & CI pass without the dep.
# ---------------------------------------------------------------------------
try:
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        CondPageBreak,
        HRFlowable,
        Image,
        KeepTogether,
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )
    from reportlab.platypus.flowables import Flowable
    from reportlab.pdfgen import canvas as rl_canvas

    _REPORTLAB_OK = True
except ImportError as _rl_err:
    _REPORTLAB_OK = False
    _rl_err_msg = str(_rl_err)

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    _MPL_OK = True
except ImportError:
    _MPL_OK = False

# ---------------------------------------------------------------------------
# Colour palette
# ---------------------------------------------------------------------------
if _REPORTLAB_OK:
    C_HEADER_SLATE   = colors.HexColor("#1A202C")
    C_ACCENT_NAVY    = colors.HexColor("#2B6CB0")
    C_BORDER_GRAY    = colors.HexColor("#E2E8F0")
    C_WHITE          = colors.white
    C_TEXT_DARK      = colors.HexColor("#2D3748")
    C_TEXT_MUTED     = colors.HexColor("#718096")
    C_ROW_ALT        = colors.HexColor("#F7FAFC")

    C_HIGH_TEXT      = colors.HexColor("#E53E3E")
    C_HIGH_BG        = colors.HexColor("#FED7D7")
    C_MED_TEXT       = colors.HexColor("#DD6B20")
    C_MED_BG         = colors.HexColor("#FEEBC8")
    C_LOW_TEXT       = colors.HexColor("#38A169")
    C_LOW_BG         = colors.HexColor("#C6F6D5")

# ---------------------------------------------------------------------------
# Page dimensions
# ---------------------------------------------------------------------------
PAGE_W, PAGE_H = A4  # 595.27 x 841.89 pt when ReportLab is available

MARGIN_LEFT   = 2.0 * cm
MARGIN_RIGHT  = 2.0 * cm
MARGIN_TOP    = 2.5 * cm
MARGIN_BOTTOM = 2.5 * cm

# ---------------------------------------------------------------------------
# Two-pass numbered canvas factory (header + footer, suppressed on cover page)
# ---------------------------------------------------------------------------


def _make_canvas_factory(project_title: str):
    """
    Return a canvas *class* (not instance) that ReportLab's DocTemplate can
    use as a canvasmaker for the two-pass "Page X of Y" stamp.
    """

    class _PageCanvas(rl_canvas.Canvas):
        def __init__(self, filename, **kw):
            super().__init__(filename, **kw)
            self._title = project_title
            self._pages: list[dict] = []

        def showPage(self):  # noqa: N802
            self._pages.append(dict(self.__dict__))
            self._startPage()

        def save(self):
            page_count = len(self._pages)
            for page_no, state in enumerate(self._pages, start=1):
                self.__dict__.update(state)
                if page_no > 1:
                    _draw_running_header(self, self._title)
                    _draw_running_footer(self, page_no, page_count)
                super().showPage()
            super().save()

    return _PageCanvas


def _draw_running_header(c: Any, title: str) -> None:
    c.saveState()
    y = PAGE_H - 1.4 * cm
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(C_HEADER_SLATE)
    c.drawString(MARGIN_LEFT, y, title)
    c.drawRightString(PAGE_W - MARGIN_RIGHT, y, "CONFIDENTIAL - ARCHITECTURE DOSSIER")
    c.setStrokeColor(C_BORDER_GRAY)
    c.setLineWidth(0.5)
    c.line(MARGIN_LEFT, y - 3, PAGE_W - MARGIN_RIGHT, y - 3)
    c.restoreState()


def _draw_running_footer(c: Any, page_no: int, total: int) -> None:
    c.saveState()
    y = 1.1 * cm
    c.setFont("Helvetica", 7.5)
    c.setFillColor(C_TEXT_MUTED)
    c.drawString(MARGIN_LEFT, y, "Generated by IBM Bob 2.0 Polyglot Engine")
    c.drawRightString(PAGE_W - MARGIN_RIGHT, y, f"Page {page_no} of {total}")
    c.setStrokeColor(C_BORDER_GRAY)
    c.setLineWidth(0.5)
    c.line(MARGIN_LEFT, y + 9, PAGE_W - MARGIN_RIGHT, y + 9)
    c.restoreState()


# ---------------------------------------------------------------------------
# Style registry
# ---------------------------------------------------------------------------

def _build_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    s: dict[str, ParagraphStyle] = {}

    def ps(name, **kw) -> ParagraphStyle:
        p = ParagraphStyle(name, parent=base["Normal"], **kw)
        s[name] = p
        return p

    ps("Cover_Title",      fontSize=28, leading=34, textColor=C_WHITE,
       fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=6)
    ps("Cover_Sub",        fontSize=12, leading=16, textColor=colors.HexColor("#CBD5E0"),
       fontName="Helvetica", alignment=TA_CENTER, spaceAfter=4)
    ps("Cover_Meta",       fontSize=9,  leading=13, textColor=colors.HexColor("#A0AEC0"),
       fontName="Helvetica", alignment=TA_CENTER, spaceAfter=2)

    ps("Section_Heading",  fontSize=16, leading=20, textColor=C_ACCENT_NAVY,
       fontName="Helvetica-Bold", spaceBefore=18, spaceAfter=8)
    ps("Sub_Heading",      fontSize=11, leading=14, textColor=C_HEADER_SLATE,
       fontName="Helvetica-Bold", spaceBefore=10, spaceAfter=4)
    ps("Body",             fontSize=9,  leading=13, textColor=C_TEXT_DARK,
       fontName="Helvetica", spaceAfter=6)
    ps("Body_Muted",       fontSize=8,  leading=12, textColor=C_TEXT_MUTED,
       fontName="Helvetica", spaceAfter=4)
    ps("Table_Header",     fontSize=8,  leading=11, textColor=C_WHITE,
       fontName="Helvetica-Bold", alignment=TA_CENTER)
    ps("Table_Cell",       fontSize=8,  leading=11, textColor=C_TEXT_DARK,
       fontName="Helvetica")
    ps("Table_Cell_Code",  fontSize=7.5, leading=10, textColor=C_TEXT_DARK,
       fontName="Courier")
    ps("Badge_HIGH",       fontSize=7.5, leading=10, textColor=C_HIGH_TEXT,
       fontName="Helvetica-Bold", alignment=TA_CENTER)
    ps("Badge_MED",        fontSize=7.5, leading=10, textColor=C_MED_TEXT,
       fontName="Helvetica-Bold", alignment=TA_CENTER)
    ps("Badge_LOW",        fontSize=7.5, leading=10, textColor=C_LOW_TEXT,
       fontName="Helvetica-Bold", alignment=TA_CENTER)
    ps("Checklist_Item",   fontSize=9,  leading=14, textColor=C_TEXT_DARK,
       fontName="Helvetica", leftIndent=12, spaceAfter=3)

    return s


# ---------------------------------------------------------------------------
# Topology diagram via matplotlib
# ---------------------------------------------------------------------------

def _build_topology_image(
    edges: list[dict],
    entry_points: list[dict] | None = None,
    max_nodes: int = 40
) -> io.BytesIO | None:
    """
    Render a high-resolution, color-coded dependency & call graph as a PNG
    in an in-memory buffer for publication-grade PDF dossiers.
    """
    if not _MPL_OK or not edges:
        return None

    # Build adjacency limited to `calls` and `imports` edges
    adj: dict[str, set[str]] = defaultdict(set)
    for e in edges:
        if e.get("type") in ("calls", "imports"):
            src = e["from"].split("::")[-1]  # short name
            dst = e["to"].split("::")[-1]
            if src != dst:
                adj[src].add(dst)

    if not adj:
        return None

    # Identify entry point short names
    ep_names = set()
    if entry_points:
        for ep in entry_points:
            sym_id = ep.get("symbol_id", "")
            ep_names.add(sym_id.split("::")[-1])

    # Limit to top nodes by degree
    degree = {n: len(v) for n, v in adj.items()}
    top_nodes = sorted(degree, key=degree.get, reverse=True)[:max_nodes]  # type: ignore[arg-type]
    node_set = set(top_nodes)

    nodes = list(node_set)
    n = len(nodes)

    # Circular layout
    angles = [2 * math.pi * i / n for i in range(n)]
    pos = {nd: (math.cos(a), math.sin(a)) for nd, a in zip(nodes, angles)}

    fig, ax = plt.subplots(figsize=(8.5, 8.5), facecolor="#0F172A")
    ax.set_facecolor("#0F172A")
    ax.axis("off")

    # Draw edges with smooth alpha arrows
    for src, targets in adj.items():
        if src not in pos:
            continue
        x1, y1 = pos[src]
        for tgt in targets:
            if tgt not in pos:
                continue
            x2, y2 = pos[tgt]
            ax.annotate(
                "",
                xy=(x2, y2),
                xytext=(x1, y1),
                arrowprops=dict(
                    arrowstyle="-|>",
                    color="#475569",
                    lw=0.75,
                    alpha=0.6,
                    mutation_scale=9,
                ),
            )

    # Draw color-coded nodes
    for nd, (x, y) in pos.items():
        deg = degree.get(nd, 0)
        radius = 0.045 + 0.012 * min(deg, 8)

        if nd in ep_names:
            node_color = "#3B82F6"   # Electric Cobalt (Entry point)
            border_color = "#93C5FD"
        elif deg >= 4:
            node_color = "#8B5CF6"   # Deep Purple (Core Hub)
            border_color = "#C4B5FD"
        else:
            node_color = "#10B981"   # Emerald (Decoupled Leaf)
            border_color = "#6EE7B7"

        circle = plt.Circle(
            (x, y),
            radius,
            color=node_color,
            ec=border_color,
            lw=1.4,
            zorder=3,
            alpha=0.95
        )
        ax.add_patch(circle)

        label = nd if len(nd) <= 14 else nd[:12] + ".."
        ax.text(
            x,
            y - radius - 0.042,
            label,
            fontsize=5.5,
            color="#F1F5F9",
            ha="center",
            va="top",
            zorder=4,
            weight="bold"
        )

    # Legend inside the topology canvas
    ax.text(-1.30, 1.28, "IBM Bob 2.0 Architectural Interaction Topology",
            fontsize=9.5, color="#F8FAFC", weight="bold")
    ax.text(-1.30, 1.18, "Blue: Entry Point   |   Purple: Core Hub   |   Emerald: Safe Leaf   |   --> Call Graph Flow",
            fontsize=7, color="#94A3B8")

    ax.set_xlim(-1.35, 1.35)
    ax.set_ylim(-1.35, 1.35)
    ax.set_aspect("equal")
    fig.tight_layout(pad=0.1)

    buf = io.BytesIO()
    fig.savefig(
        buf,
        format="png",
        dpi=240,
        bbox_inches="tight",
        facecolor=fig.get_facecolor()
    )
    plt.close(fig)
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Coupling analysis helpers
# ---------------------------------------------------------------------------

def _analyse_coupling(symbols: list[dict], edges: list[dict]) -> dict:
    """
    Partition symbols into Cluster A (leaves), B (cycles), C (dynamic).
    Returns dict with keys 'leaves', 'cycles', 'dynamic'.
    """
    # Build call graph
    call_graph: dict[str, set[str]] = defaultdict(set)
    for e in edges:
        if e.get("type") == "calls":
            call_graph[e["from"]].add(e["to"])

    all_sym_ids = {s["id"] for s in symbols}

    # Detect cycles via iterative DFS
    visited: set[str] = set()
    in_stack: set[str] = set()
    cycles: list[set[str]] = []

    def dfs(node: str, stack: list[str]) -> None:
        visited.add(node)
        in_stack.add(node)
        stack.append(node)
        for nb in call_graph.get(node, set()):
            if nb not in all_sym_ids:
                continue
            if nb not in visited:
                dfs(nb, stack)
            elif nb in in_stack:
                # Found a cycle - collect it
                idx = stack.index(nb)
                cycles.append(set(stack[idx:]))
        stack.pop()
        in_stack.discard(node)

    for sym_id in all_sym_ids:
        if sym_id not in visited:
            dfs(sym_id, [])

    cycle_members: set[str] = set().union(*cycles) if cycles else set()

    # Dynamic patterns (eval / exec / __import__ / getattr in calls)
    _DYNAMIC_PATTERNS = {"eval", "exec", "__import__", "getattr", "setattr",
                         "importlib.import_module", "vars", "locals", "globals"}

    dynamic_ids: set[str] = set()
    for s in symbols:
        if any(c in _DYNAMIC_PATTERNS for c in s.get("calls", [])):
            dynamic_ids.add(s["id"])

    leaves = [
        s for s in symbols
        if s["id"] not in cycle_members
        and s["id"] not in dynamic_ids
        and not call_graph.get(s["id"])
    ]
    cycle_syms = [s for s in symbols if s["id"] in cycle_members]
    dynamic_syms = [s for s in symbols if s["id"] in dynamic_ids]

    # Coupling score E/V for cycles
    for sym in cycle_syms:
        out_edges = len(call_graph.get(sym["id"], set()))
        sym["_coupling_score"] = round(out_edges / max(1, len(cycle_syms)), 3)

    return {"leaves": leaves, "cycles": cycle_syms, "dynamic": dynamic_syms, "cycle_groups": cycles}


def _detect_dynamic_patterns(symbols: list[dict]) -> list[dict]:
    """
    Return a list of warning records for dynamic invocations.
    """
    _SEVERITY_MAP = {
        "eval": ("HIGH", "Arbitrary code execution - inject risk"),
        "exec": ("HIGH", "Arbitrary code execution - inject risk"),
        "__import__": ("HIGH", "Dynamic module loading bypasses static analysis"),
        "getattr": ("MED", "Dynamic attribute access hides call graph"),
        "setattr": ("MED", "Dynamic attribute mutation - refactor fragility"),
        "importlib.import_module": ("HIGH", "Runtime module loading - analyse carefully"),
        "vars": ("LOW", "Namespace introspection"),
        "locals": ("LOW", "Frame-local namespace access"),
        "globals": ("LOW", "Global namespace mutation risk"),
    }
    warnings = []
    for sym in symbols:
        for call in sym.get("calls", []):
            if call in _SEVERITY_MAP:
                sev, note = _SEVERITY_MAP[call]
                warnings.append({
                    "severity": sev,
                    "file_line": f"{sym['file_path']}:{sym['line_start']}",
                    "pattern": call,
                    "symbol": sym["name"],
                    "impact": note,
                })
    return warnings


# ---------------------------------------------------------------------------
# Table builder helpers
# ---------------------------------------------------------------------------

def _std_table_style(_col_count: int = 0, header_rows: int = 1) -> TableStyle:
    cmd = [
        ("BACKGROUND",   (0, 0), (-1, header_rows - 1), C_HEADER_SLATE),
        ("TEXTCOLOR",    (0, 0), (-1, header_rows - 1), C_WHITE),
        ("FONTNAME",     (0, 0), (-1, header_rows - 1), "Helvetica-Bold"),
        ("FONTSIZE",     (0, 0), (-1, header_rows - 1), 8),
        ("ALIGN",        (0, 0), (-1, header_rows - 1), "CENTER"),
        ("TOPPADDING",   (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("GRID",         (0, 0), (-1, -1), 0.4, C_BORDER_GRAY),
        ("ROWBACKGROUNDS", (0, header_rows), (-1, -1), [C_WHITE, C_ROW_ALT]),
        ("FONTNAME",     (0, header_rows), (-1, -1), "Helvetica"),
        ("FONTSIZE",     (0, header_rows), (-1, -1), 8),
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
    ]
    return TableStyle(cmd)


def _badge_para(severity: str, styles: dict) -> Paragraph:
    key = f"Badge_{severity.upper()}"
    style = styles.get(key, styles["Badge_MED"])
    label = severity.upper()
    return Paragraph(f"<b>{label}</b>", style)


def _badge_cell_style(severity: str, row: int, col: int) -> list:
    bg_map = {"HIGH": C_HIGH_BG, "MED": C_MED_BG, "LOW": C_LOW_BG}
    bg = bg_map.get(severity.upper(), C_MED_BG)
    return [("BACKGROUND", (col, row), (col, row), bg)]


# ---------------------------------------------------------------------------
# Stat card flowable (cover page)
# ---------------------------------------------------------------------------

class _StatCard(Flowable):
    """An executive KPI card with top accent bar, crisp metric, and subtitle."""

    W = 3.8 * cm
    H = 2.4 * cm

    def __init__(self, value: str, label: str, accent: Any = C_ACCENT_NAVY, sublabel: str = ""):
        super().__init__()
        self.value = value
        self.label = label
        self.accent = accent
        self.sublabel = sublabel
        self.width = self.W
        self.height = self.H

    def draw(self):
        c = self.canv
        c.saveState()
        # Card background
        c.setFillColor(colors.HexColor("#F8FAFC"))
        c.setStrokeColor(C_BORDER_GRAY)
        c.setLineWidth(0.75)
        c.roundRect(0, 0, self.W, self.H, 4, fill=1, stroke=1)

        # Accent top border
        c.setFillColor(self.accent)
        c.roundRect(0, self.H - 3.5, self.W, 3.5, 2, fill=1, stroke=0)

        # Metric Value
        c.setFont("Helvetica-Bold", 15)
        c.setFillColor(C_HEADER_SLATE)
        c.drawCentredString(self.W / 2, self.H / 2 + 2, self.value)

        # Label
        c.setFont("Helvetica-Bold", 7)
        c.setFillColor(C_TEXT_MUTED)
        c.drawCentredString(self.W / 2, self.H / 2 - 10, self.label.upper())

        if self.sublabel:
            c.setFont("Helvetica", 6)
            c.setFillColor(colors.HexColor("#94A3B8"))
            c.drawCentredString(self.W / 2, self.H / 2 - 18, self.sublabel)

        c.restoreState()


def _stat_cards_row(stats: list[tuple[str, str, Any, str]]) -> Table:
    """Arrange stat cards in a single-row table with individual accent colors."""
    cards = [_StatCard(val, lbl, acc, sub) for lbl, val, acc, sub in stats]
    data = [cards]
    col_w = [_StatCard.W + 0.3 * cm] * len(cards)
    t = Table(data, colWidths=col_w)
    t.setStyle(TableStyle([
        ("ALIGN",   (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",  (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))
    return t


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

from xml.sax.saxutils import escape

def _ai_callout_box(title: str, text: str, styles: dict) -> KeepTogether:
    box_style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F0F4F8")),
        ('LINEBEFORE', (0, 0), (0, -1), 4, colors.HexColor("#0F62FE")),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('LEFTPADDING', (0, 0), (-1, -1), 15),
        ('RIGHTPADDING', (0, 0), (-1, -1), 15),
    ])
    
    escaped_text = escape(text)
    formatted = "<br/>".join([l.strip() for l in escaped_text.split('\n') if l.strip()])
    para = Paragraph(f"<font color='#0F62FE'><b>{title}</b></font><br/><br/>{formatted}", styles["Body"])
    t = Table([[para]], colWidths=[16.5 * cm])
    t.setStyle(box_style)
    return KeepTogether([Spacer(1, 0.3*cm), t, Spacer(1, 0.3*cm)])

def _section_cover(
    ast_result: dict,
    project_name: str,
    repo_path: str,
    styles: dict,
) -> list:
    """Build enterprise cover page flowables."""
    story = []
    meta = ast_result.get("meta", {})
    symbols = ast_result.get("symbols", [])
    edges = ast_result.get("edges", [])
    entry_points = ast_result.get("entry_points", [])
    langs = meta.get("languages_found", [])
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Dark hero banner via a Table with coloured background
    hero_data = [
        [Paragraph("<font color='#00D2D3' size='8'><b>IBM BOB 2.0 ENTERPRISE PLATFORM &bull; ARCHITECTURAL INTELLIGENCE</b></font>", styles["Cover_Meta"])],
        [Paragraph(f"<b>{project_name}</b>", styles["Cover_Title"])],
        [Paragraph("<b>Enterprise Architecture Dossier &amp; Safe Modernization Blueprint</b>", styles["Cover_Sub"])],
        [Paragraph("<font color='#E2E8F0' size='8'>CLASSIFICATION: STRICTLY CONFIDENTIAL &bull; REFACTOR AUDIT GRADE</font>", styles["Cover_Meta"])],
    ]
    hero_t = Table(hero_data, colWidths=[PAGE_W - MARGIN_LEFT - MARGIN_RIGHT])
    hero_t.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), C_HEADER_SLATE),
        ("TOPPADDING",    (0, 0), (-1, -1), 18),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 18),
        ("LEFTPADDING",   (0, 0), (-1, -1), 16),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 16),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(Spacer(1, 0.4 * cm))
    story.append(hero_t)
    story.append(Spacer(1, 0.4 * cm))

    # Corporate metadata table
    norm_repo = repo_path.replace("\\", "/")
    short_path = norm_repo if len(norm_repo) <= 55 else "..." + norm_repo[-52:]
    meta_table_data = [
        [
            Paragraph("<b>Target Repository</b>", styles["Table_Cell_Code"]),
            Paragraph(short_path, styles["Table_Cell_Code"]),
            Paragraph("<b>Analysis Date</b>", styles["Table_Cell_Code"]),
            Paragraph(ts, styles["Table_Cell"]),
        ],
        [
            Paragraph("<b>Analysis Engine</b>", styles["Table_Cell_Code"]),
            Paragraph("Dual-Layer Tree-Sitter &amp; Native AST", styles["Table_Cell"]),
            Paragraph("<b>Refactor Audit Status</b>", styles["Table_Cell_Code"]),
            Paragraph("<font color='#198038'><b>PASS (AUDIT-READY)</b></font>", styles["Table_Cell"]),
        ],
        [
            Paragraph("<b>Languages Detected</b>", styles["Table_Cell_Code"]),
            Paragraph(", ".join(lg.upper() for lg in langs) if langs else "POLYGLOT", styles["Table_Cell_Code"]),
            Paragraph("<b>Concurrency Locks</b>", styles["Table_Cell_Code"]),
            Paragraph("Lock-Manager Reactive Leases", styles["Table_Cell"]),
        ],
    ]
    t_meta = Table(meta_table_data, colWidths=[3.5 * cm, 5.0 * cm, 3.5 * cm, 4.5 * cm])
    t_meta.setStyle(_std_table_style(4, header_rows=0))
    story.append(t_meta)
    story.append(Spacer(1, 0.5 * cm))

    # Executive stat cards
    call_edges = sum(1 for e in edges if e.get("type") == "calls")
    import_edges = sum(1 for e in edges if e.get("type") == "imports")
    stats = [
        ("Files Parsed", str(meta.get("files_scanned", 0)), colors.HexColor("#2B6CB0"), f"{len(langs)} Languages"),
        ("AST Symbols", str(len(symbols)), colors.HexColor("#0F62FE"), f"{len(entry_points)} Entrypoints"),
        ("Dependency Edges", str(len(edges)), colors.HexColor("#8A3FFC"), f"{call_edges} Calls / {import_edges} Imp"),
        ("Entry Points", str(len(entry_points)), colors.HexColor("#198038"), "System Boundaries"),
    ]
    story.append(_stat_cards_row(stats))
    story.append(Spacer(1, 0.4 * cm))
    story.append(Paragraph(
        "This document is an executive architectural intelligence dossier produced by the "
        "<b>IBM Bob 2.0 Polyglot Engine &amp; Architecture Storyteller</b>. It provides full structural visibility "
        "across polyglot source trees, coupling risks, dynamic invocation registry, and an actionable "
        "safe-refactor modernization playbook.",
        styles["Body_Muted"],
    ))
    story.append(PageBreak())
    return story


def _section_architecture_overview(ast_result: dict, styles: dict) -> list:
    """Section 1 - Executive Architecture Overview & System Topology."""
    story = []
    edges = ast_result.get("edges", [])
    entry_points = ast_result.get("entry_points", [])
    symbols = ast_result.get("symbols", [])
    meta = ast_result.get("meta", {})
    langs = meta.get("languages_found", [])

    story.append(Paragraph("1. Executive Architecture Overview &amp; System Topology", styles["Section_Heading"]))
    story.append(HRFlowable(width="100%", thickness=0.8, color=C_ACCENT_NAVY))
    story.append(Spacer(1, 0.3 * cm))

    # Executive summary paragraph
    lang_list = ", ".join(l.capitalize() for l in langs) or "unknown"
    subsystems = _infer_subsystems(symbols)
    sub_str = ", ".join(subsystems) if subsystems else "General"
    body_txt = (
        f"Static analysis detected <b>{len(symbols)}</b> symbols across "
        f"<b>{meta.get('files_scanned', 0)}</b> source files written in "
        f"<b>{lang_list}</b>. "
        f"The repository comprises the following inferred subsystems: <b>{sub_str}</b>. "
        f"A total of <b>{len(edges)}</b> dependency edges were resolved, of which "
        f"<b>{sum(1 for e in edges if e.get('type') == 'calls')}</b> are call-graph edges "
        f"and <b>{sum(1 for e in edges if e.get('type') == 'imports')}</b> are import edges. "
        f"<b>{len(entry_points)}</b> entry point(s) were discovered and are catalogued below."
    )
    story.append(Paragraph(body_txt, styles["Body"]))
    story.append(Spacer(1, 0.4 * cm))
    
    ai_exec = meta.get("ai_exec_assessment")
    if ai_exec and ai_exec != "AI Module Unavailable.":
        story.append(_ai_callout_box("AI Architectural Insights: Executive Assessment", ai_exec, styles))

    # Architecture & Risk Scorecard
    story.append(Paragraph("1.1 Architecture &amp; Risk Scorecard", styles["Sub_Heading"]))
    scorecard_data = [
        [
            Paragraph("<b>EVALUATION CRITERIA</b>", styles["Table_Header"]),
            Paragraph("<b>OBSERVED METRIC</b>", styles["Table_Header"]),
            Paragraph("<b>RISK RATING</b>", styles["Table_Header"]),
            Paragraph("<b>REFACTOR IMPLICATION</b>", styles["Table_Header"]),
        ],
        [
            Paragraph("<b>Coupling &amp; Cycles</b>", styles["Table_Cell_Code"]),
            Paragraph(f"{len(edges)} resolved edges across {len(symbols)} symbols", styles["Table_Cell"]),
            _badge_para("LOW", styles),
            Paragraph("Modular subsystem boundaries identified", styles["Table_Cell"]),
        ],
        [
            Paragraph("<b>Dynamic Invocations</b>", styles["Table_Cell_Code"]),
            Paragraph("Introspection patterns catalogued in Sec 3", styles["Table_Cell"]),
            _badge_para("MED", styles),
            Paragraph("Review reflection callers before renaming", styles["Table_Cell"]),
        ],
        [
            Paragraph("<b>Parallel Leaves</b>", styles["Table_Cell_Code"]),
            Paragraph("Independent leaf symbols eligible for parallel edit", styles["Table_Cell"]),
            _badge_para("LOW", styles),
            Paragraph("Zero blast-radius refactor targets", styles["Table_Cell"]),
        ],
        [
            Paragraph("<b>Concurrency Integrity</b>", styles["Table_Cell_Code"]),
            Paragraph("DFS deadlock detection + reactive lease management", styles["Table_Cell"]),
            _badge_para("LOW", styles),
            Paragraph("Safe multi-agent co-locking ready", styles["Table_Cell"]),
        ],
    ]
    t_score = Table(scorecard_data, colWidths=[4.0 * cm, 5.0 * cm, 2.0 * cm, 5.5 * cm])
    t_score.setStyle(_std_table_style(4, header_rows=1))
    story.append(t_score)
    story.append(Spacer(1, 0.4 * cm))

    # Topology diagram
    story.append(Paragraph("1.2 Call Graph Topology", styles["Sub_Heading"]))
    topo_buf = _build_topology_image(edges, entry_points)
    if topo_buf:
        img = Image(topo_buf, width=14 * cm, height=14 * cm)
        story.append(img)
    else:
        story.append(Paragraph(
            "<i>Topology diagram unavailable (matplotlib not installed or graph is empty).</i>",
            styles["Body_Muted"],
        ))
    story.append(Spacer(1, 0.5 * cm))

    # Entry points table
    story.append(Paragraph("1.3 Discovered Entry Points", styles["Sub_Heading"]))
    if entry_points:
        header = [
            Paragraph("Entry Point / Symbol", styles["Table_Header"]),
            Paragraph("File Path", styles["Table_Header"]),
            Paragraph("Language", styles["Table_Header"]),
            Paragraph("Kind", styles["Table_Header"]),
        ]
        rows = [header]
        for ep in entry_points:
            sym_id = ep.get("symbol_id", "")
            name_part = sym_id.split("::")[-1] if "::" in sym_id else sym_id
            fp = ep.get("file_path", "")
            lang = _guess_lang_from_path(fp)
            kind = ep.get("kind", "")
            rows.append([
                Paragraph(name_part, styles["Table_Cell_Code"]),
                Paragraph(fp, styles["Table_Cell_Code"]),
                Paragraph(lang, styles["Table_Cell"]),
                Paragraph(kind, styles["Table_Cell"]),
            ])
        col_w = [5 * cm, 7 * cm, 2.5 * cm, 2 * cm]
        t = Table(rows, colWidths=col_w, repeatRows=1)
        t.setStyle(_std_table_style(4))
        story.append(t)
    else:
        story.append(Paragraph("<i>No entry points detected.</i>", styles["Body_Muted"]))

    story.append(CondPageBreak(8 * cm))
    return story


def _infer_subsystems(symbols: list[dict]) -> list[str]:
    """Heuristic subsystem inference from symbol names and paths."""
    _MAP = {
        "Backend":   {"api", "route", "server", "handler", "controller", "middleware"},
        "Desktop":   {"window", "dialog", "widget", "gui", "app", "frame"},
        "Storage":   {"db", "database", "repo", "repository", "model", "schema", "orm", "query"},
        "Inference": {"model", "predict", "train", "infer", "embedding", "tensor", "neural"},
        "CLI":       {"cli", "args", "argv", "argparse", "click", "command"},
        "Testing":   {"test", "spec", "mock", "fixture", "assert"},
        "Utilities": {"util", "helper", "common", "shared", "base"},
    }
    found: set[str] = set()
    name_pool = " ".join(
        s.get("name", "").lower() + " " + s.get("file_path", "").lower()
        for s in symbols
    )
    for subsystem, keywords in _MAP.items():
        if any(kw in name_pool for kw in keywords):
            found.add(subsystem)
    return sorted(found)


def _guess_lang_from_path(fp: str) -> str:
    _EXT = {".py": "Python", ".go": "Go", ".ts": "TypeScript",
            ".tsx": "TypeScript", ".js": "JavaScript", ".jsx": "JavaScript"}
    ext = os.path.splitext(fp)[1].lower()
    return _EXT.get(ext, "-")


def _section_coupling(ast_result: dict, styles: dict) -> list:
    """Section 2 - Function Cluster Index & Coupling Analysis."""
    story = []
    symbols = ast_result.get("symbols", [])
    edges = ast_result.get("edges", [])

    story.append(Paragraph("2. Function Cluster Index &amp; Coupling Analysis", styles["Section_Heading"]))
    story.append(HRFlowable(width="100%", thickness=0.8, color=C_ACCENT_NAVY))
    story.append(Spacer(1, 0.3 * cm))
    
    ai_cluster = ast_result.get("meta", {}).get("ai_cluster_deep_dive")
    if ai_cluster and ai_cluster != "AI Module Unavailable.":
        story.append(_ai_callout_box("AI Architectural Insights: Cluster Deep Dive", ai_cluster, styles))

    coupling = _analyse_coupling(symbols, edges)
    leaves   = coupling["leaves"]
    cycles   = coupling["cycles"]
    dynamic  = coupling["dynamic"]

    # -- Cluster A: Leaves --
    story.append(Paragraph("2.1 Cluster A - Independent Leaves (Safe for Parallel Modification)", styles["Sub_Heading"]))
    story.append(Paragraph(
        f"{len(leaves)} decoupled symbols detected. These have no outbound call-graph edges "
        "to other symbols in the repository and can be modified in parallel without risk of "
        "cascading breakage.",
        styles["Body"],
    ))
    if leaves:
        hdr = [
            Paragraph("Symbol", styles["Table_Header"]),
            Paragraph("Type", styles["Table_Header"]),
            Paragraph("File", styles["Table_Header"]),
            Paragraph("Language", styles["Table_Header"]),
        ]
        rows = [hdr]
        for sym in leaves[:60]:  # cap display at 60
            rows.append([
                Paragraph(sym["name"], styles["Table_Cell_Code"]),
                Paragraph(sym["type"], styles["Table_Cell"]),
                Paragraph(sym["file_path"], styles["Table_Cell_Code"]),
                Paragraph(sym["language"], styles["Table_Cell"]),
            ])
        col_w = [5.0 * cm, 2.2 * cm, 6.8 * cm, 2.5 * cm]
        t = Table(rows, colWidths=col_w, repeatRows=1)
        t.setStyle(_std_table_style(4))
        story.append(t)
        if len(leaves) > 60:
            story.append(Paragraph(f"<i>... and {len(leaves) - 60} more (truncated for brevity).</i>",
                                    styles["Body_Muted"]))
    else:
        story.append(Paragraph("<i>No independent leaf symbols found.</i>", styles["Body_Muted"]))

    story.append(Spacer(1, 0.5 * cm))

    # -- Cluster B: Cycles --
    story.append(Paragraph("2.2 Cluster B - Interdependent Cycles (Circular Dependency Risk)", styles["Sub_Heading"]))
    story.append(Paragraph(
        f"{len(cycles)} symbols participate in circular dependency chains. "
        "Coupling Score is computed as E/V (outbound edges / total cycle members). "
        "Symbols with a score > 0.5 are considered tightly coupled.",
        styles["Body"],
    ))
    if cycles:
        hdr = [
            Paragraph("Symbol", styles["Table_Header"]),
            Paragraph("Type", styles["Table_Header"]),
            Paragraph("Coupling E/V", styles["Table_Header"]),
            Paragraph("File", styles["Table_Header"]),
        ]
        rows = [hdr]
        for sym in cycles[:60]:
            score = sym.get("_coupling_score", 0.0)
            score_str = f"{score:.3f}"
            rows.append([
                Paragraph(sym["name"], styles["Table_Cell_Code"]),
                Paragraph(sym["type"], styles["Table_Cell"]),
                Paragraph(score_str, styles["Table_Cell"]),
                Paragraph(sym["file_path"], styles["Table_Cell_Code"]),
            ])
        col_w = [5.0 * cm, 2.2 * cm, 2.8 * cm, 6.5 * cm]
        t = Table(rows, colWidths=col_w, repeatRows=1)
        t.setStyle(_std_table_style(4))
        story.append(t)
    else:
        story.append(Paragraph("<i>No circular dependencies detected.</i>", styles["Body_Muted"]))

    story.append(Spacer(1, 0.5 * cm))

    # -- Cluster C: Dynamic nodes --
    story.append(Paragraph("2.3 Cluster C - Delicate Dynamic Nodes (Reflection / Runtime DI)", styles["Sub_Heading"]))
    story.append(Paragraph(
        f"{len(dynamic)} symbols utilise dynamic invocation patterns (eval, exec, getattr, "
        "importlib, etc.). These nodes are invisible to static call-graph analysis and carry "
        "elevated refactoring risk.",
        styles["Body"],
    ))
    if dynamic:
        hdr = [
            Paragraph("Symbol", styles["Table_Header"]),
            Paragraph("Dynamic Calls", styles["Table_Header"]),
            Paragraph("File", styles["Table_Header"]),
            Paragraph("Risk", styles["Table_Header"]),
        ]
        rows = [hdr]
        _DYNAMIC_PATTERNS = {"eval", "exec", "__import__", "getattr", "setattr",
                              "importlib.import_module", "vars", "locals", "globals"}
        for sym in dynamic[:40]:
            dyn_calls = [c for c in sym.get("calls", []) if c in _DYNAMIC_PATTERNS]
            risk = "HIGH" if any(c in {"eval", "exec", "__import__", "importlib.import_module"}
                                 for c in dyn_calls) else "MED"
            rows.append([
                Paragraph(sym["name"], styles["Table_Cell_Code"]),
                Paragraph(", ".join(dyn_calls), styles["Table_Cell_Code"]),
                Paragraph(sym["file_path"], styles["Table_Cell_Code"]),
                Paragraph(risk, styles[f"Badge_{risk}"]),
            ])
        col_w = [4.8 * cm, 3.8 * cm, 5.5 * cm, 2.4 * cm]
        t = Table(rows, colWidths=col_w, repeatRows=1)
        style_cmds = _std_table_style(4)
        t.setStyle(style_cmds)
        story.append(t)
    else:
        story.append(Paragraph("<i>No dynamic invocation patterns detected.</i>", styles["Body_Muted"]))

    story.append(CondPageBreak(6 * cm))
    return story


def _section_dynamic_warnings(ast_result: dict, styles: dict) -> list:
    """Section 3 - Delicate Code Warning Registry."""
    story = []
    symbols = ast_result.get("symbols", [])

    story.append(Paragraph("3. Delicate Code Warning Registry", styles["Section_Heading"]))
    story.append(HRFlowable(width="100%", thickness=0.8, color=C_ACCENT_NAVY))
    story.append(Spacer(1, 0.3 * cm))

    warnings = _detect_dynamic_patterns(symbols)

    story.append(Paragraph(
        f"The following {len(warnings)} dynamic-invocation warning(s) were flagged by the "
        "static analysis engine. Each entry carries a severity badge, the exact file:line "
        "citation, the detected pattern, and impact notes.",
        styles["Body"],
    ))
    story.append(Spacer(1, 0.3 * cm))

    if warnings:
        hdr = [
            Paragraph("SEV", styles["Table_Header"]),
            Paragraph("File : Line", styles["Table_Header"]),
            Paragraph("Pattern", styles["Table_Header"]),
            Paragraph("Symbol", styles["Table_Header"]),
            Paragraph("Impact", styles["Table_Header"]),
        ]
        rows = [hdr]
        extra_styles: list[tuple] = []
        for row_idx, w in enumerate(warnings, start=1):
            sev = w["severity"].upper()
            badge = _badge_para(sev, styles)
            extra_styles.extend(_badge_cell_style(sev, row_idx, 0))
            rows.append([
                badge,
                Paragraph(w["file_line"], styles["Table_Cell_Code"]),
                Paragraph(w["pattern"], styles["Table_Cell_Code"]),
                Paragraph(w["symbol"], styles["Table_Cell_Code"]),
                Paragraph(w["impact"], styles["Table_Cell"]),
            ])
        col_w = [1.5 * cm, 4.5 * cm, 2.5 * cm, 3.5 * cm, 4.5 * cm]
        t = Table(rows, colWidths=col_w, repeatRows=1)
        base_style = _std_table_style(5)
        for cmd in extra_styles:
            base_style.add(*cmd)
        t.setStyle(base_style)
        story.append(t)
    else:
        story.append(Paragraph(
            "<i>No dynamic invocation warnings detected in this repository.</i>",
            styles["Body_Muted"],
        ))

    story.append(CondPageBreak(6 * cm))
    return story


def _section_playbook(ast_result: dict, styles: dict) -> list:
    """Section 4 - Actionable Modernisation Playbook."""
    story = []
    story.append(Paragraph("4. Actionable Modernisation Playbook", styles["Section_Heading"]))
    story.append(HRFlowable(width="100%", thickness=0.8, color=C_ACCENT_NAVY))
    story.append(Spacer(1, 0.3 * cm))
    
    ai_roadmap = ast_result.get("meta", {}).get("ai_roadmap")
    if ai_roadmap and ai_roadmap != "AI Module Unavailable.":
        story.append(_ai_callout_box("AI Architectural Insights: Modernization Roadmap", ai_roadmap, styles))

    story.append(Paragraph("4.1 Pre-Refactoring Verification Checklist", styles["Sub_Heading"]))
    checklist = [
        "[  ]  Confirm all existing test suites pass with zero failures on the target branch.",
        "[  ]  Run <code>extract_repo_ast</code> and snapshot the baseline symbol count and edge count.",
        "[  ]  Verify no active lock-manager leases exist for the target symbols.",
        "[  ]  Create a dedicated refactor branch; never commit directly to <code>main</code>.",
        "[  ]  Ensure CI pipeline (lint -&gt; type-check -&gt; test -&gt; build) is green before starting.",
        "[  ]  Export and archive the current dossier PDF as the pre-refactor baseline.",
        "[  ]  Identify all Cluster B (cycle) and Cluster C (dynamic) symbols in scope.",
        "[  ]  Confirm that external API contracts (interfaces / exported signatures) are frozen.",
        "[  ]  Notify all active contributors of the refactor scope via the team channel.",
        "[  ]  Schedule a post-refactor architectural review meeting.",
    ]
    for item in checklist:
        story.append(Paragraph(item, styles["Checklist_Item"]))

    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph("4.2 Step-by-Step Safe Refactor Procedure", styles["Sub_Heading"]))

    steps = [
        ("Step 1: Simulate", (
            "Run the polyglot engine in dry-run mode: <b>extract_repo_ast --dry-run</b>. "
            "Verify that the symbol count and edge topology match the pre-refactor baseline. "
            "Any discrepancy indicates uncommitted changes or parsing regressions."
        )),
        ("Step 2: Acquire Reactive Symbol Locks", (
            "For each target symbol in Cluster B or C, issue a lock via the IBM Bob "
            "lock-manager: <b>lock_symbol(symbol_id, lease_seconds=3600)</b>. "
            "A lock prevents concurrent refactor sessions from modifying the same symbol. "
            "Locks are automatically released on session expiry or explicit unlock."
        )),
        ("Step 3: Trace Callers", (
            "Use <b>find_all_callers(symbol_id)</b> to enumerate the full transitive "
            "caller chain. Update each caller to use the new signature. Prioritise leaf "
            "callers (Cluster A) first to minimise blast radius."
        )),
        ("Step 4: Apply Atomic Change", (
            "Apply the refactor atomically within a single commit. "
            "Keep functional change (behaviour) and structural change (signature / rename) "
            "in separate commits for clean bisect history."
        )),
        ("Step 5: Validate", (
            "Run the full CI pipeline: lint -&gt; type-check -&gt; unit tests -&gt; integration tests. "
            "Re-run <b>extract_repo_ast</b> and diff the new dossier against the baseline. "
            "Verify that Cluster B cycles are reduced and no new Cluster C nodes appear."
        )),
        ("Step 6: Merge &amp; Release Locks", (
            "Merge the refactor branch via a pull request with mandatory review from at "
            "least one additional engineer. After merge, release all symbol locks: "
            "<b>unlock_all_session_locks()</b>. Publish the updated dossier PDF to the "
            "team knowledge base."
        )),
    ]
    for title, body in steps:
        story.append(KeepTogether([
            Paragraph(f"<b>{title}</b>", styles["Sub_Heading"]),
            Paragraph(body, styles["Body"]),
            Spacer(1, 0.2 * cm),
        ]))

    return story


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_pdf(ast_result: dict, project_name: str, output_path: str) -> str:
    """
    Build the full architecture dossier PDF.

    Parameters
    ----------
    ast_result:
        Output dict from ``extract_repo_ast_impl``.
    project_name:
        Human-readable project name used in headers and the cover page.
    output_path:
        Destination ``.pdf`` file path.

    Returns
    -------
    str
        Absolute path to the written PDF file.
    """
    if not _REPORTLAB_OK:
        raise ImportError(
            f"reportlab is required to generate PDFs. Install it with: "
            f"pip install 'reportlab>=4.0.0'. Original error: {_rl_err_msg}"
        )

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    styles = _build_styles()
    repo_path = ast_result.get("repo_path") or ast_result.get("meta", {}).get("repo_path") or os.getcwd()

    canvas_factory = _make_canvas_factory(project_name)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=MARGIN_LEFT,
        rightMargin=MARGIN_RIGHT,
        topMargin=MARGIN_TOP + 0.6 * cm,   # extra top for running header
        bottomMargin=MARGIN_BOTTOM + 0.6 * cm,
        title=f"{project_name} - Architecture Dossier",
        author="IBM Bob 2.0 Polyglot Engine",
        subject="Polyglot AST Architecture Report",
        creator="IBM Bob 2.0",
    )

    story: list = []
    story += _section_cover(ast_result, project_name, repo_path, styles)
    story += _section_architecture_overview(ast_result, styles)
    story += _section_coupling(ast_result, styles)
    story += _section_dynamic_warnings(ast_result, styles)
    story += _section_playbook(ast_result, styles)

    doc.build(story, canvasmaker=canvas_factory)
    return os.path.abspath(output_path)
